/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author angel
 */
public class AgregarAcademica extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAcademica
     */
    public AgregarAcademica() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        frameHoraTermino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        frameMinutosTermino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        frameSala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        frameHoraInicio = new javax.swing.JTextField();
        frameMinutosInicio = new javax.swing.JTextField();
        labelSeleccionHora = new javax.swing.JLabel();
        labelSeleccionMinutos = new javax.swing.JLabel();
        labelSeleccionHoraTermino = new javax.swing.JLabel();
        labelSeleccionMinutosTermino = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText(":");

        jLabel6.setText(":");

        frameHoraTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameHoraTerminoActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar actividad academica");

        frameMinutosTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameMinutosTerminoActionPerformed(evt);
            }
        });

        jLabel2.setText(" - Hora inicio :");

        frameSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameSalaActionPerformed(evt);
            }
        });

        jLabel3.setText(" - Hora termino :");

        jLabel4.setText(" - Sala :");

        frameHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameHoraInicioActionPerformed(evt);
            }
        });

        frameMinutosInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameMinutosInicioActionPerformed(evt);
            }
        });

        labelSeleccionHora.setText(".");

        labelSeleccionMinutos.setText(".");

        labelSeleccionHoraTermino.setText(".");

        labelSeleccionMinutosTermino.setText(".");

        jButton1.setText("Agregar.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSeleccionHoraTermino)
                .addGap(52, 52, 52)
                .addComponent(labelSeleccionMinutosTermino)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frameHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frameMinutosTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frameSala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSeleccionHora)
                                        .addGap(52, 52, 52)
                                        .addComponent(labelSeleccionMinutos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frameHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frameMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(frameHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frameMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionHora)
                    .addComponent(labelSeleccionMinutos))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(frameHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frameMinutosTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionHoraTermino)
                    .addComponent(labelSeleccionMinutosTermino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(frameSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frameHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameHoraInicioActionPerformed
        if(seleccionHora(Integer.parseInt(frameHoraInicio.getText()))){    
            horaInicio = Integer.parseInt(frameHoraInicio.getText());
            labelSeleccionHora.setText(".");
        }else
            labelSeleccionHora.setText("*Hora invalida.");
    }//GEN-LAST:event_frameHoraInicioActionPerformed

    private void frameMinutosInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameMinutosInicioActionPerformed
        if(seleccionMinutos(Integer.parseInt(frameMinutosInicio.getText()))){
            minutosInicio = Integer.parseInt(frameMinutosInicio.getText());
            labelSeleccionMinutos.setText(".");
        }else
            labelSeleccionMinutos.setText("*Minutos invalidos.");
    }//GEN-LAST:event_frameMinutosInicioActionPerformed

    private void frameHoraTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameHoraTerminoActionPerformed
        if(seleccionHora(Integer.parseInt(frameHoraTermino.getText()))){
            horaTermino = Integer.parseInt(frameHoraTermino.getText());
            labelSeleccionHoraTermino.setText(".");
        }else
            labelSeleccionHoraTermino.setText("*Hora invalida.");
    }//GEN-LAST:event_frameHoraTerminoActionPerformed

    private void frameMinutosTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameMinutosTerminoActionPerformed
        if(seleccionMinutos(Integer.parseInt(frameMinutosInicio.getText()))){
            minutosInicio = Integer.parseInt(frameMinutosInicio.getText());
            labelSeleccionMinutosTermino.setText(".");
        }else
            labelSeleccionMinutosTermino.setText("*Minutos invalidos.");
    }//GEN-LAST:event_frameMinutosTerminoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean cumple = false;
        if(seleccionMinutos(minutosInicio) && seleccionMinutos(minutosTermino) && seleccionHora(horaInicio) && seleccionHora(horaTermino))
            cumple = true;
        if(cumple){
            Academica actividadAcademica = new Academica();
            actividadAcademica.setHoraInicio(horaInicio);
            actividadAcademica.setMinutosInicio(minutosInicio);
            actividadAcademica.setHoraTermino(horaTermino);
            actividadAcademica.setMinutosTermino(minutosTermino);
            actividadAcademica.setSala(sala);
            new Aviso().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void frameSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameSalaActionPerformed
        sala = frameSala.getText();
    }//GEN-LAST:event_frameSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAcademica().setVisible(true);
            }
        });
    }
    public boolean seleccionHora(int seleccion) {
            if (seleccion < 0 || seleccion > 24){
                return false;
            }else
                return true;
    }
    public boolean seleccionMinutos(int seleccion) {
            if (seleccion < 0 || seleccion > 60){
                return false;
            }else
                return true;
    }
    private int horaInicio;
    private int minutosInicio;
    private int horaTermino;
    private int minutosTermino;
    private String sala;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField frameHoraInicio;
    private javax.swing.JTextField frameHoraTermino;
    private javax.swing.JTextField frameMinutosInicio;
    private javax.swing.JTextField frameMinutosTermino;
    private javax.swing.JTextField frameSala;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelSeleccionHora;
    private javax.swing.JLabel labelSeleccionHoraTermino;
    private javax.swing.JLabel labelSeleccionMinutos;
    private javax.swing.JLabel labelSeleccionMinutosTermino;
    // End of variables declaration//GEN-END:variables
}
